// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyGlobalVariables.h"
#include "BunjilandGlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDialogues_Mycelia_S01Variables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Dialogues_Mycelia_S01")
	UArticyBool* E01_PlayerKayleSpoken = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Dialogues_Mycelia_S01")
	UArticyBool* E01_PlayerKayleInterrupted = nullptr;
	
	 UBunjilandDialogues_Mycelia_S01Variables() 
	{
		E01_PlayerKayleSpoken = CreateDefaultSubobject<UArticyBool>("E01_PlayerKayleSpoken");
		E01_PlayerKayleInterrupted = CreateDefaultSubobject<UArticyBool>("E01_PlayerKayleInterrupted");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		E01_PlayerKayleSpoken->Init<UArticyBool>(this, Store, TEXT("Dialogues_Mycelia_S01.E01_PlayerKayleSpoken"), false);
		this->Variables.Add(E01_PlayerKayleSpoken);
		E01_PlayerKayleInterrupted->Init<UArticyBool>(this, Store, TEXT("Dialogues_Mycelia_S01.E01_PlayerKayleInterrupted"), false);
		this->Variables.Add(E01_PlayerKayleInterrupted);
	}
};

UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDialogues_Desert_S01Variables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	
	 UBunjilandDialogues_Desert_S01Variables() 
	{
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Dialogues_Mycelia_S01")
	UBunjilandDialogues_Mycelia_S01Variables* Dialogues_Mycelia_S01 = nullptr;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Dialogues_Desert_S01")
	UBunjilandDialogues_Desert_S01Variables* Dialogues_Desert_S01 = nullptr;
	
	 UBunjilandGlobalVariables() 
	{
		/** create the namespaces */
		Dialogues_Mycelia_S01 = CreateDefaultSubobject<UBunjilandDialogues_Mycelia_S01Variables>("Dialogues_Mycelia_S01");
		Dialogues_Desert_S01 = CreateDefaultSubobject<UBunjilandDialogues_Desert_S01Variables>("Dialogues_Desert_S01");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		Dialogues_Mycelia_S01->Init(this);
		this->VariableSets.Add(Dialogues_Mycelia_S01);
		Dialogues_Desert_S01->Init(this);
		this->VariableSets.Add(Dialogues_Desert_S01);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UBunjilandGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UBunjilandGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
