// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyDatabase.h"
#include "BunjilandExpressoScripts.h"
#include "BunjilandDatabase.generated.h"

UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 UBunjilandDatabase() 
	{
		SetExpressoScriptsClass(UBunjilandExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UBunjilandDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UBunjilandDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UBunjilandGlobalVariables* GetGVs() const override
	{
		return static_cast<UBunjilandGlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UBunjilandGlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UBunjilandGlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
