// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyExpressoScripts.h"
#include "BunjilandGlobalVariables.h"
#include "BunjilandExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class UBunjilandMethodsProvider : public UInterface { GENERATED_BODY() };
class IBunjilandMethodsProvider
{
	GENERATED_BODY()
	
public:
};

UCLASS(BlueprintType, Blueprintable)
class BUNJILAND_API UBunjilandExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	mutable TWeakObjectPtr<UBunjilandDialogues_Mycelia_S01Variables> Dialogues_Mycelia_S01 = nullptr;
	mutable TWeakObjectPtr<UBunjilandDialogues_Desert_S01Variables> Dialogues_Desert_S01 = nullptr;
	mutable TWeakObjectPtr<UBunjilandGlobalVariables> ActiveGlobals = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<UBunjilandGlobalVariables>(GV);
		/** Initialize all GV namespace references (or nullify if we're setting to nullptr) */
		Dialogues_Mycelia_S01 = gv ? gv->Dialogues_Mycelia_S01 : nullptr;
		Dialogues_Desert_S01 = gv ? gv->Dialogues_Desert_S01 : nullptr;
		/** Store GVs */
		ActiveGlobals = gv;
	}
	
	UArticyGlobalVariables* GetGV() override
	{
		/** Return active global variables as set by SetGV */
		if(ActiveGlobals.IsValid()) { return ActiveGlobals.Get(); }
		return nullptr;
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return UBunjilandMethodsProvider::StaticClass();
	}
	
public:
	
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	#endif
	 UBunjilandExpressoScripts() 
	{
		Conditions.Add(1923961472, [&]
		{
			return ConditionOrTrue(
				(*Dialogues_Mycelia_S01->E01_PlayerKayleSpoken) == true
			);
		});
		Conditions.Add(410602364, [&]
		{
			return ConditionOrTrue(
				(*Dialogues_Mycelia_S01->E01_PlayerKayleSpoken) == false
			);
		});
		Instructions.Add(2079910838, [&]
		{
			(*Dialogues_Mycelia_S01->E01_PlayerKayleSpoken) = true;
		});
		Conditions.Add(734078552, [&]
		{
			return ConditionOrTrue(
				(*Dialogues_Mycelia_S01->E01_PlayerKayleInterrupted) == true
			);
		});
	}
	#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
	#pragma warning(pop)
	#endif
};
