// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyBaseInclude.h"
#include "BunjilandInterfaces.h"
#include "BunjilandArticyTypes.generated.h"


/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef Sex */
class EBunjilandSex : uint8
{
	Male = 0,
	Female = 1,
	Unknown = 2,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef ShapeType */
class EBunjilandShapeType : uint8
{
	Invalid = 0,
	Spot = 1,
	Circle = 2,
	Rectangle = 3,
	Path = 4,
	Polygon = 5,
	Link = 6,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef SelectabilityModes */
class EBunjilandSelectabilityModes : uint8
{
	Unselectable = 0,
	Selectable = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef VisibilityModes */
class EBunjilandVisibilityModes : uint8
{
	Invisible = 0,
	Visible = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef OutlineStyle */
class EBunjilandOutlineStyle : uint8
{
	Solid = 0,
	Dot = 1,
	Dash = 2,
	DashDot = 3,
	DashDotDot = 4,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef PathCaps */
class EBunjilandPathCaps : uint8
{
	ColoredDot = 0,
	None = 1,
	LineArrowHead = 2,
	FilledArrowHead = 3,
	Diamond = 4,
	Square = 5,
	Disc = 6,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef LocationAnchorSize */
class EBunjilandLocationAnchorSize : uint8
{
	Small = 0,
	Medium = 1,
	Large = 2,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef PreviewImageViewBoxModes */
class EBunjilandPreviewImageViewBoxModes : uint8
{
	FromAsset = 0,
	Custom = 1,
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef FlowFragment */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandFlowFragment : public UArticyFlowFragment,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Dialogue */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDialogue : public UArticyDialogue,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef DialogueFragment */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDialogueFragment : public UArticyDialogueFragment,
 public IArticyObjectWithMenuText,
 public IArticyObjectWithStageDirections,
 public IArticyObjectWithSpeaker,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="MenuText"))
	FText MenuText = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StageDirections"))
	FText StageDirections = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Speaker"))
	FArticyId Speaker;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Hub */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandHub : public UArticyHub,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Comment */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandComment : public UArticyComment,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedBy"))
	FString CreatedBy = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedOn"))
	FDateTime CreatedOn;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Jump */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandJump : public UArticyJump,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Entity */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandEntity : public UArticyEntity,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Basic Character Properties Feature */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDefaultBasicCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Age"))
	float Age = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Species"))
	FText Species = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Born in"))
	FText BornIn = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Sex"))
	EBunjilandSex Sex;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Profession"))
	FText Occupation = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Voice"))
	FText Accent = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Personality"))
	FText Personality = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Appearance"))
	FText Appearance = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Playable Character"))
	bool PlayableCharacter = false;
};
/** UCLASS generated from ArticyObjectDef DefaultSupportingCharacterTemplate */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDefaultSupportingCharacterTemplate : public UBunjilandEntity,
 public IBunjilandObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** IBunjilandObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UBunjilandDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UBunjilandDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Extended Character Properties Feature */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDefaultExtendedCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Goals"))
	FText Motivation = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Inner Conflict"))
	FText InnerConflict = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Skills"))
	FText Skills = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Weaknesses"))
	FText Fears = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Quirks / Habits"))
	FText Habits = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Further Details"))
	FText FurtherDetails = FText::GetEmpty();
};
/** UCLASS generated from ArticyObjectDef DefaultMainCharacterTemplate */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDefaultMainCharacterTemplate : public UBunjilandEntity,
 public IBunjilandObjectWithDefaultExtendedCharacterFeatureFeature,
 public IBunjilandObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** IBunjilandObjectWithDefaultExtendedCharacterFeatureFeature implementation */
	UBunjilandDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const override
	{
		return DefaultExtendedCharacterFeature;
	}
	/** IBunjilandObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UBunjilandDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Extended Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UBunjilandDefaultExtendedCharacterFeatureFeature* DefaultExtendedCharacterFeature;
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UBunjilandDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Location */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandLocation : public UArticyLocation,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Spot */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandSpot : public UArticySpot,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EBunjilandVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EBunjilandOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EBunjilandSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Zone */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandZone : public UArticyZone,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EBunjilandShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EBunjilandVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EBunjilandOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EBunjilandSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Path */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandPath : public UArticyPath,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EBunjilandVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EBunjilandSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EBunjilandOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StartCap"))
	EBunjilandPathCaps StartCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="EndCap"))
	EBunjilandPathCaps EndCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="LineWidth"))
	float LineWidth = 0.f;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Link */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandLink : public UArticyLink,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithTarget,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Target"))
	FArticyId Target;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EBunjilandVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EBunjilandSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Asset */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandAsset : public UArticyAsset,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Filename"))
	FString Filename = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OriginalSource"))
	FString OriginalSource = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Condition */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandCondition : public UArticyCondition,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptCondition* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Instruction */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandInstruction : public UArticyInstruction,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptInstruction* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationText */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandLocationText : public UArticyLocationText,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EBunjilandShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EBunjilandVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EBunjilandOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EBunjilandSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedWidth"))
	float ForcedWidth = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedHeight"))
	float ForcedHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationImage */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandLocationImage : public UArticyLocationImage,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EBunjilandShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EBunjilandVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EBunjilandOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EBunjilandSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ClipRect"))
	FArticyRect ClipRect;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageOpacity"))
	float ImageOpacity = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageAsset"))
	FArticyId ImageAsset;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageWidth"))
	int32 CachedImageWidth = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageHeight"))
	int32 CachedImageHeight = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Document */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandDocument : public UArticyDocument,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef TextObject */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandTextObject : public UArticyTextObject,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef UserFolder */
UCLASS(BlueprintType)
class BUNJILAND_API UBunjilandUserFolder : public UArticyUserFolder,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithShortId,
 public IArticyObjectWithZIndex
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
};
